default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "queue_0"
      threads: <%= ENV.fetch("QUEUE_THREADS", 1) %>
      processes: <%= ENV.fetch("QUEUE_WORKERS", 1) %>
      polling_interval: 0.1

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
