default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "queue_0"
      threads: 5
      processes: 1
      polling_interval: 0.1
    - queues: "queue_1"
      threads: 5
      processes: 1
      polling_interval: 0.1
    - queues: "queue_2"
      threads: 5
      processes: 1
      polling_interval: 0.1
    - queues: "queue_3"
      threads: 5
      processes: 1
      polling_interval: 0.1
    - queues: "queue_4"
      threads: 5
      processes: 1
      polling_interval: 0.1
    - queues: "queue_5"
      threads: 5
      processes: 1
      polling_interval: 0.1
    - queues: "queue_6"
      threads: 5
      processes: 1
      polling_interval: 0.1
    - queues: "queue_7"
      threads: 5
      processes: 1
      polling_interval: 0.1

development:
 <<: *default

test:
 <<: *default

production:
 <<: *default
